#!/bin/bash
# runs rellum*.C for each run to look at how bXing distributions change

if [ $# -ne 2 ]; then
  echo "Usage: $0 [drawLog] [zoomIn]"
  exit
else
  drawLog=$1
  zoomIn=$2
fi


cat fill.txt | awk '{print $1}' | uniq > run_list.txt



job="rundep.bat"
> $job

echo "building batch file.."
echo "Executable = `which root.exe`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="log"
wd=$(pwd)

cnt=1

while read run; do
  echo "Arguments = -b -q rellum4.C(\\\"bx\\\",1,$drawLog,$zoomIn,0,$run)" >> $job
  echo "Log    = ${log}/RellumRun${cnt}.log" >> $job
  echo "Output = ${log}/RellumRun${cnt}.out" >> $job
  echo "Error  = ${log}/RellumRun${cnt}.err" >> $job
  echo "Queue" >> $job
  echo "" >> $job
  let cnt++
done < run_list.txt

condor_submit $job
