#!/bin/bash
# runs rellum*.C for each fill to look at how bXing distributions change

drawLog=0
zoomIn=0 


cat fill.txt | awk '{print $1}' | uniq > run_list.txt



job="filldep.bat"
> $job

echo "building batch file.."
echo "Executable = `which root.exe`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="log"
wd=$(pwd)

cnt=1

while read run; do
  echo "Arguments = -b -q rellum4.C(\\\"bx\\\",1,$drawLog,$zoomIn,0,$run)" >> $job
  echo "Log    = ${log}/RellumFill${cnt}.log" >> $job
  echo "Output = ${log}/RellumFill${cnt}.out" >> $job
  echo "Error  = ${log}/RellumFill${cnt}.err" >> $job
  echo "Queue" >> $job
  echo "" >> $job
  let cnt++
done < run_list.txt

condor_submit $job
